<?php

function smartdocs_service_services_resources() {
    watchdog( 'smartdocs', "Entering the service.");

    return array(
	'smartdocs' => array(
	    'actions' => array(
		'render' => array(
		    'help' => 'Render SmartDocs page',
		    'file' => array(
		            'type' => 'inc',
            	            'module' => 'smartdocs_service',
                            'name' => 'smartdocs_service',
                          ), 
                    'callback' => '_smartdocs_service_swagger_render',
		    'access callback' => 'user_access',
		    'access arguments' => array('render and publish model'),
		    'access arguments append' => FALSE,
		    'args' => array(
			array(
			    'name' => 'modeluuid',
			    'type' => 'string',
			    'description' => 'Model uuid',
			    'source' => array( 'param' => 'modeluuid' ),
			    'optional' => FALSE,
			),
			array(
			    'name' => 'revision',
			    'type' => 'string',
			    'description' => 'Model revision',
			    'source' => array( 'param' => 'revision' ),
			    'optional' => FALSE,
			),
		    ),
		),
		'import' => array(
		    'help' => 'Import Swagger file. POST mltipart/form-data',
		    'file' => array(
	                'type' => 'inc',
        	        'module' => 'smartdocs_service',
                        'name' => 'smartdocs_service',
            	    ), 
                    'callback' => '_smartdocs_service_swagger_import',
		    'access callback' => 'user_access',
		    'access arguments' => array('import swagger specification'),
		    'args' => array(
			array(
			    'name' => 'model',
			    'type' => 'string',
			    'description' => 'Model name',
			    'source' => array( 'data' => 'model' ),
			    'optional' => TRUE,
			    'default' => '<page>'
			),
			array(
			    'name' => 'type',
			    'optional' => FALSE,
			    'source' => array('data' => 'type'),
			    'description' => 'The swagger file type, "yaml" or "json"',
			    'type' => 'string',
			),
		    ),
		),
	    ),
	)
    );

}

function smartdocs_service_permission() {
    return array(
	'import swagger specification' => array(
	    'title' => t('Import Swagger specification')
	    ),
	'render and publish model' => array(
	    'title' => t('Render And Publish Model')
	    )
	);
}

function _smartdocs_access($op, $args){
    return TRUE;
}


?>
